-- AlterTable
ALTER TABLE "Album" ALTER COLUMN "name" DROP NOT NULL,
ALTER COLUMN "artistName" DROP NOT NULL,
ALTER COLUMN "artworkUrl" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Song" ALTER COLUMN "name" DROP NOT NULL,
ALTER COLUMN "artistName" DROP NOT NULL,
ALTER COLUMN "albumName" DROP NOT NULL;
